services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://agrotech_owner:qoxdLHJQ05ap@ep-calm-king-a4hfu7tm.us-east-1.aws.neon.tech/agrotech?sslmode=require
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: agrotech_owner
      POSTGRES_PASSWORD: qoxdLHJQ05ap
      POSTGRES_DB: agrotech
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
